spring:
  data:
    mongodb:
      auto-index-creation: false
      host: localhost
      database: news
      port: 27017
  application:
    name: News
logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              ReactiveMongoTemplate: DEBUG
news:
  api:
    key: ""

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs

server:
  servlet:
    context-path: /news